import SimpleSchema from 'simpl-schema';

/**
 * @summary Thriver File Download Namespace
 * @namespace Thriver.files
 */
Thriver.files = {};

/**
 * @summary Files collection
 * @type {Mongo.Collection}
 */
Thriver.files.collection = new Mongo.Collection('files');

/**
 * @summary Files collection schema
 * @type {SimpleSchema}
 */
Thriver.files.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** File name */
  fileName: {
    type: String,
    optional: false,
  },
  /** File ID */
  fileId: {
    type: Number,
    optional: false,
  },
});

// Apply schema to collection
Thriver.files.collection.attachSchema(Thriver.files.schema);
