language: node_js
node_js: "7"

before_install:
  # install meteor
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"

env:
  - PATH=$HOME/.meteor:$PATH

services: mongodb

script:
  # lint time!
  - meteor npm run lint
