import SimpleSchema from 'simpl-schema';

/**
 * @summary Learning Center namespace
 * @namespace Thriver.newsroom
 */
Thriver.learningCenter = {};

/**
 * @summary Learning Center collection
 * @type {Mongo.Collection}
 */
Thriver.learningCenter.collection = new Mongo.Collection('learningCenter');

/**
 * @summary Learning Center Schema
 * @type {SimpleSchema}
 */
Thriver.learningCenter.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
    autoform: {
      type: 'hidden',
    },
  },
  /** Item Title */
  title: {
    type: String,
    optional: false,
  },
  /** Item Link */
  url: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
  },
  /** Item Publisher (like for webinar items) */
  publisher: {
    type: String,
    optional: true,
  },
  /** Item Date */
  date: {
    type: Date,
    optional: false,
    defaultValue: new Date(),
  },
  /** Item Type */
  type: {
    type: String,
    optional: false,
    allowedValues: [
      'infosheet',
      'webinar',
    ],
  },
  /** Category */
  category: {
    type: String,
    optional: true,
    autoform: {
      type: 'hidden',
    },
  },
  /** Item Description */
  description: {
    type: String,
    optional: true,
  },
});

// Apply schema to collection
Thriver.learningCenter.collection.attachSchema(Thriver.learningCenter.schema);
