import SimpleSchema from 'simpl-schema';
import { Mongo } from 'meteor/mongo';

/**
 * @summary Resource Center namespace
 * @namespace
 */
const Resources = {};

/**
 * @summary Resource Center collection
 * @type {Mongo.Collection}
 */
Resources.collection = new Mongo.Collection('resources');

/**
 * @summary Resource Center Schema
 * @type {SimpleSchema}
 */
Resources.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
    autoform: {
      type: 'hidden',
    },
  },
  /** Item Title */
  title: {
    type: String,
    optional: false,
  },
  /** Item Link */
  url: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
  },
  /** Item Publisher (like for webinar items) */
  publisher: {
    type: String,
    optional: true,
  },
  /** Item Date */
  date: {
    type: Date,
    optional: false,
    defaultValue: new Date(),
  },
  /** Item Type */
  type: {
    type: String,
    optional: false,
    allowedValues: [
      'infosheet',
      'webinar',
      'library'
    ],
  },
  /** Category */
  category: {
    type: String,
    optional: true,
    autoform: {
      type: 'hidden',
    },
  },
  /** Item Description */
  description: {
    type: String,
    optional: true,
  },
});

// Apply schema to collection
Resources.collection.attachSchema(Resources.schema);

export default Resources;
