/**
 * @summary Events namespace
 * @type {Object}
 */
Thriver.events = {};

/**
 * @summary Events collection
 * @type {Mongo.Collection}
 */
Thriver.events.collection = new Mongo.Collection('events');

/**
 * @summary Events schema
 * @type {SimpleSchema}
 */
Thriver.events.schema = new SimpleSchema({
    /** ID */
    _id: {
        type: String,
        optional: true // ID is autogenerated
    },
    /** Event Name */
    name: {
        type: String,
        optional: false
    },
    /** Event description */
    description: {
        type: String,
        optional: false,
        autoform: {
            rows: 5
        }
    },
    /** Starting datetime */
    start: {
        type: Date,
        optional: false,
        autoform: {
            type: 'datetime-local'
        }
    },
    /** Ending datetime */
    end: {
        type: Date,
        optional: true,
        autoform: {
            type: 'datetime-local'
        }
    },
    /** Lat/Lon Coordinates for Physical locations */
    location: {
        type: Object,
        optional: false,
        defaultValue: {}
    },
    'location.latitude': {
        type: Number,
        decimal: true,
        optional: true
    },
    'location.longitude': {
        type: Number,
        decimal: true,
        optional: true
    },
    /** Event address, which could be physical or web address */
    address: {
        type: String,
        optional: false
    },
    /** Cost Tiers */
    cost: {
        type: Array,
        defaultValue: [],
        optional: false
    },
    'cost.$': {
        type: Object
    },
    'cost.$.cost': {
        type: Number,
        decimal: true,
        optional: false,
        defaultValue: 0
    },
    'cost.$.description': {
        type: String,
        optional: false
    },
    'cost.$.order': {
        type: Number,
        optional: false,
        defaultValue: 0
    },
    /** Event HREF for Online Locations */
    href: {
        type: String,
        regEx: SimpleSchema.RegEx.Url,
        optional: true
    }
});
Thriver.events.collection.attachSchema(Thriver.events.schema);
