import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';

/**
 * @summary Newsroom namespace
 */
const News = {};

/**
 * @summary Newsroom collection
 * @type {Mongo.Collection}
 */
News.collection = new Mongo.Collection('newsroom');

/**
 * @summary Newsroom Schema
 * @type {SimpleSchema}
 */
News.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** Item Title */
  title: {
    type: String,
    optional: false,
  },
  /** Item Title */
  friendlyTitle: {
    type: String,
    optional: false,
  },
  /** Item Date */
  date: {
    type: Date,
    optional: false,
    defaultValue: new Date(),
  },
  /** Item Link */
  url: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
  },
  /** Item Publisher (like for In The News items) */
  publisher: {
    type: String,
    optional: true,
  },
  /** Item Type */
  type: {
    type: String,
    optional: false,
    allowedValues: [
      'actionAlert',
      'inTheNews',
      'pressRelease',
      'newsletter',
    ],
  },
  /** Item Content (like for Press Releases) */
  content: {
    type: String,
    optional: true,
  },
  description: {
    type: String,
    optional: true,
  },
});

// Apply schema to collection
News.collection.attachSchema(News.schema);

export default News;
