/**
 * @summary Providers namespace
 * @namespace
 */
Thriver.providers = {};

/**
 * @summary SASPs and Counties Collections
 * @type {Mongo.Collection}
 */
Thriver.providers.collection = new Mongo.Collection('providers');
Thriver.providers.counties = new Mongo.Collection('counties');

/**
 * @summary Providers Schema
 * @type {SimpleSchema}
 */
Thriver.providers.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** Provider name */
  name: {
    type: String,
    optional: false,
  },
  /** Counties Covered by this Provider */
  counties: {
    type: [String],
    defaultValue: [],
    label: 'Counties Served by Provider',
  },
  /** Provider's Address */
  address: {
    type: String,
    optional: false,
  },
  /** Coordinates of Provider Location */
  coordinates: {
    type: [Number],
    optional: false,
    defaultValue: [0, 0],
    label: 'Latitude and Longitude',
  },
  /** Provider Main Phone Number */
  phone: {
    type: String,
    optional: false,
    regEx: /^\(\d{3}\) \d{3}\-\d{4}.*/,
    label: 'Main Phone Number',
  },
  /** Crisis Phone Number */
  crisis: {
    type: String,
    optional: false,
    regEx: /^\(\d{3}\) \d{3}\-\d{4}.*/,
    label: '24-hr Crisis Phone Number',
  },
  /** Contact email address */
  email: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Email,
  },
  /** Website */
  website: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Website URL',
  },
  /** Facebook link */
  facebook: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Facebook Page URL',
  },
  /** Twitter feed */
  twitter: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Twitter Feed URL',
  },
});
Thriver.providers.collection.attachSchema(Thriver.providers.schema);
