import { Mongo } from 'meteor/mongo';
import SimpleSchema from 'simpl-schema';

/**
 * @summary Thriver File Download Namespace
 */
const Files = {};

/**
 * @summary Files collection
 * @type {Mongo.Collection}
 */
Files.collection = new Mongo.Collection('files');

/**
 * @summary Files collection schema
 * @type {SimpleSchema}
 */
Files.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** File name */
  fileName: {
    type: String,
    optional: false,
  },
  /** File ID */
  fileId: {
    type: Number,
    optional: false,
  },
});

// Apply schema to collection
Files.collection.attachSchema(Files.schema);

export default Files;
