import SimpleSchema from 'simpl-schema';
import { Mongo } from 'meteor/mongo';

/**
 * @summary Providers namespace
 * @namespace
 */
const Providers = {};

/**
 * @summary SASPs and Counties Collections
 * @type {Mongo.Collection}
 */
Providers.collection = new Mongo.Collection('providers');
Providers.counties = new Mongo.Collection('counties');

// Create custom validation messages
SimpleSchema.setDefaultMessages({
  messages: {
    en: {
      invalidLatitude: 'Latitude must be between 42.5 and 47.083',
      invalidLongitude: 'Longitude must be between -86.767 and -92.883',
    },
  },
});

/**
 * @summary Providers Schema
 * @type {SimpleSchema}
 */
Providers.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
    autoform: {
      type: 'hidden',
    },
  },
  /** Provider name */
  name: {
    type: String,
    optional: false,
  },
  /** Counties Covered by this Provider */
  counties: {
    type: Array,
    defaultValue: [],
    optional: false,
    label: 'Counties Served by Provider',
    autoform: {
      type: 'select-checkbox',
    },
  },
  'counties.$': {
    type: String,
    allowedValues: [
      'Adams', 'Ashland', 'Barron', 'Bayfield', 'Brown',
      'Buffalo', 'Burnett', 'Calumet', 'Chippewa', 'Clark',
      'Columbia', 'Crawford', 'Dane', 'Dodge', 'Door',
      'Douglas', 'Dunn', 'Eau Claire', 'Florence', 'Fond Du Lac',
      'Forest', 'Grant', 'Green', 'Green Lake', 'Iowa',
      'Iron', 'Jackson', 'Jefferson', 'Juneau', 'Kenosha',
      'Kewaunee', 'La Crosse', 'Lafayette', 'Langlade', 'Lincoln',
      'Manitowoc', 'Marathon', 'Marinette', 'Marquette', 'Menominee',
      'Milwaukee', 'Monroe', 'Oconto', 'Oneida', 'Outagamie',
      'Ozaukee', 'Pepin', 'Pierce', 'Polk', 'Portage',
      'Price', 'Racine', 'Richland', 'Rock', 'Rusk',
      'Saint Croix', 'Sauk', 'Sawyer', 'Shawano', 'Sheboygan',
      'Taylor', 'Trempealeau', 'Vernon', 'Vilas', 'Walworth',
      'Washburn', 'Washington', 'Waukesha', 'Waupaca', 'Waushara',
      'Winnebago', 'Wood',
    ],
  },
  /** Provider's Address */
  address: {
    type: String,
    optional: false,
    autoform: {
      type: 'textarea',
      rows: 4,
    },
  },
  /** Coordinates of Provider Location */
  coordinates: {
    type: Object,
    optional: false,
    minCount: 2,
    maxCount: 2,
  },
  'coordinates.lat': {
    type: Number,
    optional: false,
    custom: function () { // eslint-disable-line object-shorthand,func-names
      if (this.value < 42.5 || this.value > 47.083) {
        return 'invalidLatitude';
      }
      return true;
    },
    label: 'Latitude',
  },
  'coordinates.lon': {
    type: Number,
    optional: false,
    custom: function () { // eslint-disable-line object-shorthand,func-names
      if (this.value > -86.767 || this.value < -92.883) {
        return 'invalidLongitude';
      }
      return true;
    },
    label: 'Longitude',
  },

  /** Provider Main Phone Number */
  phones: {
    type: Array,
    defaultValue: [],
    optional: false,
  },
  'phones.$': {
    type: Object,
  },
  'phones.$.number': {
    type: String,
    optional: false,
    label: 'Main Phone Number',
    autoValue: function () { //eslint-disable-line
      // can't use arrow function because of `this` context
      return this.value.replace(/[^\d]/g, '');
    },
    autoform: {
      type: 'tel',
      placeholder: '+1 (123) 456-7890',
    },
  },
  'phones.$.description': {
    type: String,
    optional: true,
  },
  'phones.$.tty': {
    type: Boolean,
    optional: true,
    label: 'Is this number TTY-enabled?',
    autoform: {
      type: 'boolean-radios',
    },
  },
  'phones.$.ext': {
    type: Number,
    optional: true,
  },

  /** Crisis Phone Number */
  crisis: {
    type: Object,
    optional: false,
    defaultValue: {},
  },
  'crisis.number': {
    type: String,
    optional: false,
    label: '24-hr Crisis Phone Number',
    autoValue: function () { //eslint-disable-line
      // can't use arrow function because of `this` context
      return this.value.replace(/[^\d]/g, '');
    },
    autoform: {
      type: 'tel',
      placeholder: '+1 (123) 456-7890',
    },
  },
  'crisis.tty': {
    type: Boolean,
    optional: true,
    label: 'Is this number TTY-enabled?',
    autoform: {
      type: 'boolean-radios',
    },
  },
  'crisis.ext': {
    type: Number,
    optional: true,
  },

  /** Contact email address */
  emails: {
    type: Array,
    optional: false,
    defaultValue: [],
  },
  'emails.$': {
    type: Object,
    optional: true,
  },
  'emails.$.address': {
    type: String,
    optional: false,
    regEx: SimpleSchema.RegEx.Email,
    autoform: {
      type: 'email',
    },
  },
  'emails.$.description': {
    type: String,
    optional: true,
  },

  /** Website */
  website: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Website URL',
    autoform: {
      type: 'url',
    },
  },
  /** Facebook link */
  facebook: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Facebook Page URL',
    autoform: {
      type: 'url',
    },
  },
  /** Twitter feed */
  twitter: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Twitter Feed URL',
    autoform: {
      type: 'url',
    },
  },

  /** Notes */
  notes: {
    type: String,
    optional: true,
    autoform: {
      type: 'textarea',
      rows: 6,
    },
  },

  /** Parent Location, if this is a satellite office */
  parent: {
    type: String,
    optional: true,
    label: 'If this is a satellite office, select the Parent Location:',
    autoform: {
      options: () => {
        const parents = [];

        Providers.collection.find().forEach((provider) => {
          // If we're doing an update
          if (Providers.formMethod.get() === 'updateProvider'
              && Providers.active.get()) {
            // and the provider being edited is this provider, skip
            if (provider._id === Providers.active.get()._id) return;
          }

          // Otherwise add as a suitable parent
          parents.push({ label: provider.name, value: provider._id });
        });

        return parents;
      },
    },
    autoValue: function () { // eslint-disable-line
      // AutoForm won't pass undefined or empty string values for update
      // So we'll just use null instead to ensure parent can be unset,
      // not just changed to something else
      if (this.value === undefined) return null;
      return this.value;
    },
  },
});
Providers.collection.attachSchema(Providers.schema);

export default Providers;
