import SimpleSchema from 'simpl-schema';
import { Mongo } from 'meteor/mongo';

/**
 * @summary Providers namespace
 * @namespace
 */
const Providers = {};

/**
 * @summary SASPs and Counties Collections
 * @type {Mongo.Collection}
 */
Providers.collection = new Mongo.Collection('providers');
Providers.counties = new Mongo.Collection('counties');

// Create custom validation messages
SimpleSchema.setDefaultMessages({
  messages: {
    en: {
      invalidLatitude: 'Latitude must be between 42.5 and 47.083',
      invalidLongitude: 'Longitude must be between -86.767 and -92.883',
    },
  },
});

/**
 * @summary Providers Schema
 * @type {SimpleSchema}
 */
Providers.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** Provider name */
  name: {
    type: String,
    optional: false,
  },
  /** Counties Covered by this Provider */
  counties: {
    type: Array,
    defaultValue: [],
    optional: false,
    label: 'Counties Served by Provider',
  },
  'counties.$': {
    type: String,
    allowedValues: [
      'Adams', 'Ashland', 'Barron', 'Bayfield', 'Brown',
      'Buffalo', 'Burnett', 'Calumet', 'Chippewa', 'Clark',
      'Columbia', 'Crawford', 'Dane', 'Dodge', 'Door',
      'Douglas', 'Dunn', 'Eau Claire', 'Florence', 'Fond Du Lac',
      'Forest', 'Grant', 'Green', 'Green Lake', 'Iowa',
      'Iron', 'Jackson', 'Jefferson', 'Juneau', 'Kenosha',
      'Kewaunee', 'La Crosse', 'Lafayette', 'Langlade', 'Lincoln',
      'Manitowoc', 'Marathon', 'Marinette', 'Marquette', 'Menominee',
      'Milwaukee', 'Monroe', 'Oconto', 'Oneida', 'Outagamie',
      'Ozaukee', 'Pepin', 'Pierce', 'Polk', 'Portage',
      'Price', 'Racine', 'Richland', 'Rock', 'Rusk',
      'Saint Croix', 'Sauk', 'Sawyer', 'Shawano', 'Sheboygan',
      'Taylor', 'Trempealeau', 'Vernon', 'Vilas', 'Walworth',
      'Washburn', 'Washington', 'Waukesha', 'Waupaca', 'Waushara',
      'Winnebago', 'Wood',
    ],
  },
  /** Provider's Address */
  address: {
    type: String,
    optional: false,
  },
  /** Coordinates of Provider Location */
  coordinates: {
    type: Object,
    optional: false,
    minCount: 2,
    maxCount: 2,
  },
  'coordinates.lat': {
    type: Number,
    optional: false,
    custom: function () { // eslint-disable-line object-shorthand,func-names
      if (this.value < 42.5 || this.value > 47.083) {
        return 'invalidLatitude';
      }
      return true;
    },
    label: 'Latitude',
  },
  'coordinates.lon': {
    type: Number,
    optional: false,
    custom: function () { // eslint-disable-line object-shorthand,func-names
      if (this.value > -86.767 || this.value < -92.883) {
        return 'invalidLongitude';
      }
      return true;
    },
    label: 'Longitude',
  },

  /** Provider Main Phone Number */
  phones: {
    type: Array,
    defaultValue: [],
    optional: false,
  },
  'phones.$': {
    type: Object,
  },
  'phones.$.number': {
    type: String,
    optional: false,
    label: 'Main Phone Number',
    autoValue: function () { //eslint-disable-line
      // can't use arrow function because of `this` context
      return this.value.replace(/[^\d]/g, '');
    },
  },
  'phones.$.description': {
    type: String,
    optional: true,
  },
  'phones.$.tty': {
    type: Boolean,
    optional: true,
    label: 'Is this number TTY-enabled?',
  },
  'phones.$.ext': {
    type: Number,
    optional: true,
  },

  /** Crisis Phone Number */
  crisis: {
    type: Object,
    optional: false,
    defaultValue: {},
  },
  'crisis.number': {
    type: String,
    optional: false,
    label: '24-hr Crisis Phone Number',
    autoValue: function () { //eslint-disable-line
      // can't use arrow function because of `this` context
      return this.value.replace(/[^\d]/g, '');
    },
  },
  'crisis.tty': {
    type: Boolean,
    optional: true,
    label: 'Is this number TTY-enabled?',
  },
  'crisis.ext': {
    type: Number,
    optional: true,
  },

  /** Contact email address */
  emails: {
    type: Array,
    optional: false,
    defaultValue: [],
  },
  'emails.$': {
    type: Object,
    optional: true,
  },
  'emails.$.address': {
    type: String,
    optional: false,
    regEx: SimpleSchema.RegEx.Email,
  },
  'emails.$.description': {
    type: String,
    optional: true,
  },

  /** Website */
  website: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Website URL',
  },
  /** Facebook link */
  facebook: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Facebook Page URL',
  },
  /** Twitter feed */
  twitter: {
    type: String,
    optional: true,
    regEx: SimpleSchema.RegEx.Url,
    label: 'Twitter Feed URL',
  },

  /** Notes */
  notes: {
    type: String,
    optional: true,
  },

  /** Parent Location, if this is a satellite office */
  parent: {
    type: String,
    optional: true,
    label: 'If this is a satellite office, select the Parent Location:',
  },
});

Providers.collection.attachSchema(Providers.schema);

export default Providers;
