import SimpleSchema from 'simpl-schema';
import { Mongo } from 'meteor/mongo';

/**
 * @summary Feedback namespace
 * @namespace
 */
const Feedback = {};

/**
 * @summary Feedback collection
 * @type {Mongo.Collection}
 */
Feedback.collection = new Mongo.Collection('feedback');

/**
 * @summary Feedback schema
 * @type {SimpleSchema}
 */
Feedback.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** Element path */
  path: {
    type: String,
    optional: true,
  },
  /** Comments */
  comments: {
    type: String,
    optional: false,
  },
  /** User ID */
  userId: {
    type: String,
    optional: false,
  },
});

// Apply schema to collection
Feedback.collection.attachSchema(Feedback.schema);

export default Feedback;
