import SimpleSchema from 'simpl-schema';
import { Mongo } from 'meteor/mongo';

/**
 * @summary People Namespace
 * @namespace
 */
const People = {};

/**
 * @summary People Collection
 * @type {Mongo.Collection}
 */
People.collection = new Mongo.Collection('people');

/**
 * @summary People Schema
 * @type {SimpleSchema}
 */
People.schema = new SimpleSchema({
  /** ID */
  _id: {
    type: String,
    optional: true, // ID is autogenerated
  },
  /** Person's name and credentials */
  name: {
    type: String,
    optional: false,
  },
  /** Person's job title */
  title: {
    type: String,
    optional: false,
  },
  /** Email address */
  email: {
    type: String,
    optional: false,
    regEx: SimpleSchema.RegEx.Email,
  },
  /** Is this person a board member? */
  boardMember: {
    type: Boolean,
    optional: false,
  },
  /** Picture or Avatar */
  // TODO(micchickenburger): Consider making this a Binary Blob at some point
  picture: {
    type: String,
    optional: true,
  },
});

/** Attach schema */
People.collection.attachSchema(People.schema);

export default People;
